namespace DepinTracker.Domain.Entities;

using DepinTracker.Domain.ValueObjects;

/// <summary>
/// An aggregated position in a single token: the total quantity held and, when
/// prices are available, its current fiat value and average acquisition value.
/// Generated by analytics from imported rewards; never stored as source data.
/// </summary>
public sealed class Holding
{
    public string TokenSymbol { get; set; } = string.Empty;
    public decimal Quantity { get; set; }

    /// <summary>Current valuation, when a price is available.</summary>
    public Money? CurrentValue { get; set; }

    /// <summary>Average fiat value per token at acquisition, when computable.</summary>
    public Money? AverageAcquisitionValue { get; set; }
}
